name: Generate & Deploy BREADS Docs

on:
  push:
    branches: [main]
    # don’t retrigger on index.md-only commits
    paths-ignore:
      - "docs/**/index.md"
      - ".github/workflows/generate-and-deploy.yml"

permissions:
  contents: write

jobs:
  build-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true # so we can push

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Generate all docs/index.md files
        run: python scripts/generate_docs_index.py

      - name: Commit & push generated content
        run: |
          git config user.name "bread-bot"
          git config user.email "bread-bot@users.noreply.github.com"
          # Stage everything in docs/ (indexes + any new/changed md or ignores)
          git add docs
          # Also stage .indexignore if you added/edited them
          git add docs/**/.indexignore || true

          # Only commit if there’s _any_ change under docs/
          if git diff --cached --quiet; then
            echo "✅ No docs changes to commit"
          else
            git commit -m "🔁 Auto-generate docs index and sync ignores"
            git push origin HEAD:main
          fi
